services:
  app:
    build: .
    ports:
      - "8080:8080"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mind_tips
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

volumes:
  db:
    driver: local